In [0]:
import numpy as np
#https://zh.wikipedia.org/wiki/NumPy

In [0]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [0]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a = np.array([1,3,6,9])
b = np.linspace(0,15,4)#https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace
b

array([ 0.,  5., 10., 15.])

In [0]:
c = a-b
c

array([ 1., -2., -4., -6.])

In [0]:
a**2

array([ 1,  9, 36, 81])

In [0]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [0]:
np.linalg.inv(a)
#https://www.smwenku.com/a/5b8d7e462b717718833e68ed
#https://matrixcalc.org/zh/

LinAlgError: ignored

In [0]:
a2 = np.array([[1., 2.],[3., 4.]])
np.linalg.inv(a2)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [0]:
#https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html
#https://ipreacher.github.io/2017/common-symbolic-calculations/
a3 = np.array([[3,1],[1,2]])
b = np.array([9,8])
#3 * x0 + x1 = 9
#x0 + 2 * x1 = 8
x = np.linalg.solve(a3, b)
x
# b.shape

array([2., 3.])

In [0]:
c = np.random.rand(3,3)
c

array([[0.43823359, 0.75584546, 0.85565306],
       [0.38277954, 0.74060566, 0.78929595],
       [0.2076895 , 0.52877377, 0.82551641]])

In [0]:
np.dot(a,c)

array([[ 1.82686118,  3.8233781 ,  4.91079418],
       [ 4.91296908,  9.89905279, 12.32219043],
       [ 7.99907697, 15.97472748, 19.73358668]])

In [0]:
z = np.zeros((2,4),np.uint8)
type(z)

numpy.ndarray

In [0]:
z

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)

In [0]:
o = np.ones((2,4),np.int32)
o

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [0]:
m = np.array([[4,12,3,1],[10,12,14,29]],np.float32)
m

array([[ 4., 12.,  3.,  1.],
       [10., 12., 14., 29.]], dtype=float32)

In [0]:
m.shape

(2, 4)

In [0]:
m.dtype

dtype('float32')

In [0]:
m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]]],np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]]], dtype=float32)

In [0]:
m = np.array([[14,12,3,1],[10,12,114,29],[67,23,534,2]],np.float32)
m[1,3]

29.0

In [0]:
m[2,:]

array([ 67.,  23., 534.,   2.], dtype=float32)

In [0]:
m[0:2,1:3]

array([[ 12.,   3.],
       [ 12., 114.]], dtype=float32)

In [0]:
m = np.array([[[1,2,3,4],[5,6,7,8]],[[10,11,12,14],[15,16,17,18]],[[11,12,43,32],[1,5,10,23]]], np.float32)
m

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12., 14.],
        [15., 16., 17., 18.]],

       [[11., 12., 43., 32.],
        [ 1.,  5., 10., 23.]]], dtype=float32)

In [0]:
m[:,:,0]
# dimension*w*l

array([[ 1.,  5.],
       [10., 15.],
       [11.,  1.]], dtype=float32)

In [0]:
#m[:,:,0].shape

In [0]:
m[0,:,:]

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [0]:
src1 = np.array([[23,123,90],[100,250,0]], np.uint8)
src2 = np.array([[125,150,60],[100,10,40]], np.uint8)
dst = src1 + src2
dst

array([[148,  17, 150],
       [200,   4,  40]], dtype=uint8)

In [0]:
src2 = np.array([[125,150,60],[100,10,40]], np.float32)
dst = src1 + src2
dst

array([[148., 273., 150.],
       [200., 260.,  40.]], dtype=float32)

In [0]:
src2 = np.array([[125,150,60],[100,10,40]], np.uint8)
dst = src1 - src2
dst

array([[154, 229,  30],
       [  0, 240, 216]], dtype=uint8)

In [0]:
src2 = np.array([[125,150,60],[100,10,40]], np.float32)
dst = src1 * src2
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [0]:
dst = np.multiply(src1,src2)
dst

array([[ 2875., 18450.,  5400.],
       [10000.,  2500.,     0.]], dtype=float32)

In [0]:
src2 = np.array([[125,150,60],[100,10,40]], np.uint8)
dst = src2 / src1
dst

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[5.43478261, 1.2195122 , 0.66666667],
       [1.        , 0.04      ,        inf]])

In [0]:
3/2

1.5

In [0]:
src3 = np.array([[1,2,3],[4,5,6]],np.uint8)
src4 = np.array([[6,5],[4,3],[2,1]],np.uint8)
dst = np.dot(src3, src4)
dst

array([[20, 14],
       [56, 41]], dtype=uint8)

In [0]:
src5 = np.array([[6,5],[4,3]],np.uint8)
dst2 = np.log(src5)
dst2.dtype

dtype('float16')

In [0]:
dst2

array([[1.792, 1.609],
       [1.387, 1.099]], dtype=float16)

In [0]:
src = np.array([[30,40],[10,100]],np.uint8)
dst1 = np.power(src,2)
dst1

array([[132,  64],
       [100,  16]], dtype=uint8)

In [0]:
dst2 = np.power(src, 2.0)
dst2

array([[  900.,  1600.],
       [  100., 10000.]])

In [0]:
dst2.dtype

dtype('float64')